### ISSUE TITLE
Asyncronous?

### ISSUE THREAD

**Issue by najamelan** [brunocodutra/ring-channel#13]
thanks for making this. I was looking for a kind of unbouded drop channel. However I compose a lot with Streams and Sinks from futures-rs 0.3. 

Since on crates this has the asynchronous category, I wondered how to use that, since these traits don't seem to be implemented for RingReceiver and RingSender...

**Comment by brunocodutra** [comment]
I'm happy to hear it's useful to you.

> these traits don't seem to be implemented for RingReceiver and RingSender.

[They actually are!](https://github.com/brunocodutra/ring-channel/blob/afcce3eaae51998e7bb6361fefd9f58974afccbf/src/futures.rs)

I plan to release ring-channel v0.3 today and the futures api will be available behind a future flag `futures_api`, stay tuned.

**Comment by najamelan** [comment]
Oh, so cool, thanks. I hadn't seen because I looked at the docs.rs and I couldn't find it. Look forward to playing around with these channels...

**Comment by brunocodutra** [comment]
[v0.3](https://crates.io/crates/ring-channel) is out and includes [experimental support for the futures api](https://docs.rs/ring-channel/0.3.0/ring_channel/#experimental-features) :tada:
