### ISSUE TITLE
Would it be possible to relax `RingSender::send`'s `&mut self` to `&self`?

### ISSUE THREAD

**Issue by jesdazrez** [brunocodutra/ring-channel#131]
Hi there!, first of all thanks for the cool library :)
I was taking a quick look at the src of the `send` function and wondered if the mutable `self` reference is actually needed?

For additional context, I'm trying to use the `RingSender` in a closure that must implement `Fn`.

**Comment by brunocodutra** [comment]
Good question, I can't think of a reason why it couldn't take `&self`.

**Comment by brunocodutra** [comment]
@jesdazrez I've just released this change on v0.12.

**Comment by jesdazrez** [comment]
thanks a lot @brunocodutra!
