### ISSUE TITLE
Cargo audit warning: spin is no longer actively maintained

### ISSUE THREAD

**Issue by internetionals** [brunocodutra/ring-channel#54]
Not necessarily a bug, but something that showed up in our CI when we added support for this terrific crate.

Warning from `cargo audit`:

```txt
warning: 1 warning found
Crate:  spin
Title:  spin is no longer actively maintained
Date:   2019-11-21
URL:    https://rustsec.org/advisories/RUSTSEC-2019-0031
Dependency tree: 
spin 0.5.2
└── ring-channel 0.8.1
```

**Comment by brunocodutra** [comment]
Thanks for the heads-up! 

Didn't actually know `cargo audit` was a thing, could you point me to your CI setup so I can do something similar on my end?

**Comment by internetionals** [comment]
@brunocodutra I can share you our CI config, but it's specific for Gitlab CI. But our lint check is (apart from the Gitlab CI logic) effectively a simple run of `cargo audit` using the `ekidd/rust-musl-builder` container image.
